### ISSUE TITLE
LookupError("No installed app with label '%s'." % app_label)

### ISSUE THREAD

**Issue by hero007asd** [sshwsfc/xadmin#229]
在新加一个用户后，重新用新加的用户登录，报错:
No installed app with label 'app'.

Request Method:     GET
Request URL:    http://*****:9000/xadmin
Django Version:     1.7
Exception Type:     LookupError
Exception Value:    

No installed app with label 'app'.

Exception Location:     /root/mars/local/lib/python2.7/site-packages/django/apps/registry.py in get_app_config, line 150
# 服务器信息:

Traceback (most recent call last):
  File "/root/mars/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/sites.py", line 291, in wrapper
    return self.admin_view(view, cacheable)(_args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/sites.py", line 199, in inner
    return view(request, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 257, in view
    return handler(request, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 587, in get
    self.widgets = self.get_widgets()
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 73, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 42, in filter_chain
    return func()
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 67, in _inner_method
    return func(self, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 564, in get_widgets
    return self.get_init_widget()
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 73, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 42, in filter_chain
    return func()
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 67, in _inner_method
    return func(self, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 526, in get_init_widget
    portal_col.append(self.get_widget(widget))
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 73, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 42, in filter_chain
    return func()
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/base.py", line 67, in _inner_method
    return func(self, _args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 510, in get_widget
    wid_instance = widget_with_perm(self, data or widget.get_value())
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 319, in __init__
    super(ModelBaseWidget, self).**init**(dashboard, data)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 196, in **init**
    if not self.is_valid():
  File "/root/mars/local/lib/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/root/mars/local/lib/python2.7/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/root/mars/local/lib/python2.7/site-packages/django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "/root/mars/local/lib/python2.7/site-packages/django/forms/forms.py", line 368, in _clean_fields
    value = field.clean(value)
  File "/root/mars/local/lib/python2.7/site-packages/django/forms/fields.py", line 150, in clean
    value = self.to_python(value)
  File "/root/mars/local/lib/python2.7/site-packages/xadmin/views/dashboard.py", line 295, in to_python
    return models.get_model(app_label, model_name)
  File "/root/mars/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 54, in alias
    return getattr(loading, function_name)(_args, *_kwargs)
  File "/root/mars/local/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/root/mars/local/lib/python2.7/site-packages/django/apps/registry.py", line 150, in get_app_config
    raise LookupError("No installed app with label '%s'." % app_label)
LookupError: No installed app with label 'app'.

**Comment by ronaldgreeff** [comment]
So uh.... what was the problem and how did you resolve it?
