### ISSUE TITLE
Custom views register

### ISSUE THREAD

**Issue by alexsilva** [sshwsfc/xadmin#322]
The problem occurs when running the command `runserver 8080` and django starts to make validations in the system.

branch `master`
django `1.9.6`

```
Unhandled exception in thread started by <function wrapper at 0x044B25F0>
Traceback (most recent call last):
  File "...\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "...\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "...\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "...\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "...\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "...\django\core\checks\urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "...\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "...\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "...\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "...\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "...\Python2.7\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "project\urls.py", line 9, in <module>
    url(r'^', include(xadmin.site.urls))
  File "...\xadmin\sites.py", line 320, in urls
    return self.get_urls(), self.name, self.app_name
  File "...\xadmin\sites.py", line 302, in get_urls
    name=name) for path, clz_or_func, name in self._registry_views
  File "...\xadmin\views\base.py", line 480, in __init__
    super(ModelAdminView, self).__init__(request, *args, **kwargs)
  File "...\xadmin\views\base.py", line 231, in __init__
    self.request_method = request.method.lower()
AttributeError: 'AdminSite' object has no attribute 'method'
```

**Comment by alexsilva** [comment]
The problem was caused by the following implementation

```
from django.views.generic import FormView
from xadmin.views import ModelAdminView

class MyModelView(ModelAdminView, FormView):
    ""Custom admin view: Inherits two views that have metaclasses"

xadmin.site.register_view(r'^myapp/myapp/add/$', MyModelView, name='myapp_myapp_add')
```

[And the fix for the error](https://github.com/sshwsfc/xadmin/pull/296/commits/73ca597eb36fd38c7234c86aa2d2547ba11d0082)


However as there metaclass conflict is necessary to solve this inheriting the involved metaclasses.

```
from django.views.generic.edit import FormMixinBase
from xadmin.sites import MergeAdminMetaclass

class Metaclass(FormMixinBase, MergeAdminMetaclass):
    """Resolve conflito de metaclass"""
```


The final solution

```
from django.views.generic import FormView
from xadmin.views import ModelAdminView
from django.views.generic.edit import FormMixinBase
from xadmin.sites import MergeAdminMetaclass
from django.utils import six

class Metaclass(FormMixinBase, MergeAdminMetaclass):
    """Resolve conflito de metaclass"""

class MyModelView(six.with_metaclass(Metaclass, ModelAdminView, FormView):
    ""Custom admin view: Inherits two views that have metaclasses"

xadmin.site.register_view(r'^myapp/myapp/add/$', MyModelView, name='myapp_myapp_add')

```

I hope you understand the problem I had and because sometimes you may need to inherit from more than one view.
