### ISSUE TITLE
django 1.9 issue " ImportError: No module named"

### ISSUE THREAD

**Issue by mwolff44** [sshwsfc/xadmin#347]
I just install and configures xadmin, but when i want to test it i have an error. I work with django 1.9 and the master version of xadmin :

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/venv/local/lib/python2.7/site-packages/xadmin/apps.py", line 14, in ready
    self.module.autodiscover()
  File "/usr/local/venv/local/lib/python2.7/site-packages/xadmin/__init__.py", line 50, in autodiscover
    mod = import_module(app)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named MyAppConfig

**Comment by y2kconnect** [comment]
you see 
https://github.com/y2kconnect/xadmin-for-python3.git

this is no error. (test and demo_app)
for py2.7 or py3.4, django v1.9

**Comment by mwolff44** [comment]
OK, thanks for your answer. Is your modifs will be integrated in main project ?

**Comment by y2kconnect** [comment]
Maybe.
Has been submitted.

**Comment by wangzhaohe** [comment]
**I use python2.7 django1.10.4**

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/apps.py", line 14, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/__init__.py", line 50, in autodiscover
    mod = import_module(app)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ResumeConfig

in settings.INSTALLED_APPS:

    'resume.apps.ResumeConfig',
    # 'resume',

When use 'resume', no error, but there is no resume app records in xadmin interface.

**Comment by y2kconnect** [comment]
Please check your settings in django admin first. Then, again in the xadmin test.In addition, xadmin only supports <= django v1.9.x.来自我的华为手机-------- 原始邮件 --------主题：Re: [sshwsfc/xadmin] django 1.9 issue " ImportError: No module named" (#347)发件人：wangzhaohe 收件人：sshwsfc/xadmin 抄送：y2k connect ,Comment I use python2.7 django1.10.4
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
fn(args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
autoreload.raise_last_exception()
File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
six.reraise(_exception)
File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
fn(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/init.py", line 27, in setup
apps.populate(settings.INSTALLED_APPS)
File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 115, in populate
app_config.ready()
File "/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/apps.py", line 14, in ready
self.module.autodiscover()
File "/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/init.py", line 50, in autodiscover
mod = import_module(app)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
ImportError: No module named ResumeConfig
in settings.INSTALLED_APPS:
'resume.apps.ResumeConfig',
# 'resume',

When use 'resume', no error, but there is no resume app records in xadmin interface.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sshwsfc/xadmin","title":"sshwsfc/xadmin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sshwsfc/xadmin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wangzhaohe in #347: **I use python2.7 django1.10.4**\r\n\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py\", line 226, in wrapper\r\n    fn(*args, **kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py\", line 113, in inner_run\r\n    autoreload.raise_last_exception()\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py\", line 249, in raise_last_exception\r\n    six.reraise(*_exception)\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py\", line 226, in wrapper\r\n    fn(*args, **kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/__init__.py\", line 27, in setup\r\n    apps.populate(settings.INSTALLED_APPS)\r\n  File \"/usr/local/lib/python2.7/dist-packages/django/apps/registry.py\", line 115, in populate\r\n    app_config.ready()\r\n  File \"/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/apps.py\", line 14, in ready\r\n    self.module.autodiscover()\r\n  File \"/usr/local/lib/python2.7/dist-packages/xadmin-0.6.1-py2.7.egg/xadmin/__init__.py\", line 50, in autodiscover\r\n    mod = import_module(app)\r\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\r\n    __import__(name)\r\nImportError: No module named ResumeConfig\r\n\r\nin settings.INSTALLED_APPS:\r\n\r\n    'resume.apps.ResumeConfig',\r\n    # 'resume',\r\n\r\nWhen use 'resume', no error, but there is no resume app records in xadmin interface."}],"action":{"name":"View Issue","url":"https://github.com/sshwsfc/xadmin/issues/347#issuecomment-278850984"}}}

**Comment by y2kconnect** [comment]
Please check the resume / adminx.py file to see
Xadmin.site.register (ResumeConfig)
or
Xadmin.site.register (ResumeConfig, ResumeConfigAdmin)
does it exist?

**Comment by y2kconnect** [comment]
Not for the time being.
At present, xadmin v3.0 is being used to rewrite the response, the
change will be great. Not particularly necessary to fight things, it is
estimated will not merge into. Moreover, xadmin-for-python3 only
supports django v1.9.x, after the version is not supported. So it should
not be merged.
