### ISSUE TITLE
python3 兼容性问题

### ISSUE THREAD

**Issue by franklyx** [sshwsfc/xadmin#375]
确定对py3进行的处理吗，为什么里面的很多语法还是py2的？？

**Comment by anonmily** [comment]
我好像也遇到 python3 的問題了，若試圖用 python3 的話，就有下面這個問題：

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/xadmin/__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "/usr/local/lib/python3.6/site-packages/xadmin/sites.py", line 9, in <module>
    reload(sys)
NameError: name 'reload' is not defined
```

**Comment by xuyafei9303** [comment]
一样的问题  据说还不支持3.X？？？

**Comment by cupen** [comment]
见 #346，去帮忙 review 一下。

**Comment by tesla4321** [comment]
这个我也遇到了，需要import imp然后用imp.reload(sys)

**Comment by gitmeteor** [comment]
这么然后怎么弄 ?
依然会报：AttributeError: module 'sys' has no attribute 'setdefaultencoding'

**Comment by cupen** [comment]
参考下这里： https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script
个人以为可以直接去掉 `sys.setdefaultencoding` 这种 hack 代码，反正它也并没有真正解决编码问题。我在实际工作中，无论 py2 py3 只需设置好系统的 locale 就行，即便在 crontab 或 supervisor 里跑也只需设置好 locale （用 LANG 这个环境变量），而这也是放之四海而皆准的正常做法。

**Comment by WangXang** [comment]
貌似对py3的支持，还不太好
