### ISSUE TITLE
不支持Django==1.11

### ISSUE THREAD

**Issue by pc10201** [sshwsfc/xadmin#387]
环境python 2.7.13
Django==1.11

报错信息
```
Traceback (most recent call last):
  File "D:\Python2\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "D:\Python2\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "D:\Python2\lib\site-packages\django\utils\autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "D:\Python2\lib\site-packages\django\utils\autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "D:\Python2\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Python2\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.ready()
  File "D:\python_project\serverlist\xadmin\apps.py", line 14, in ready
    self.module.autodiscover()
  File "D:\python_project\serverlist\xadmin\__init__.py", line 27, in autodiscover
    from xadmin.views import register_builtin_views
  File "D:\python_project\serverlist\xadmin\views\__init__.py", line 5, in <module>
    from edit import CreateAdminView, UpdateAdminView, ModelFormAdminView
  File "D:\python_project\serverlist\xadmin\views\edit.py", line 16, in <module>
    from xadmin import widgets
  File "D:\python_project\serverlist\xadmin\widgets.py", line 6, in <module>
    from django.forms.widgets import RadioFieldRenderer, RadioChoiceInput
ImportError: cannot import name RadioFieldRenderer
```

**Comment by dongdong1972** [comment]
django 1.11 Lib\site-packages\django\forms\widgets.py 中已经没有了RadioFieldRenderer这个类
好多类已经修改，建议使用django低版本

**Comment by pyufftj** [comment]
同样遇到了这个问题，真是崩溃了。。我用的即是python3.6，又是django1.11，使用xadmin简直就是坑中套坑

**Comment by ideashooter** [comment]
有解吗？我也遇到了。。。

**Comment by wgbbiao** [comment]
主线已经支持了．

**Comment by hengdai** [comment]
并没有支持啊，咋回事撒

**Comment by 378978764** [comment]
并没有支持，为什么随便close?

**Comment by ileadall42** [comment]
@378978764 因为这个项目已经停止啦。
