### ISSUE TITLE
连接xadmin超时。点击‘管理登录’或登陆后进‘管理后台’，总是连接超时，长时间没有反应。多试几次，偶尔又可以进dashboard，求思路。

### ISSUE THREAD

**Issue by apprentice1985** [sshwsfc/xadmin#409]
{% if user.is_authenticated %}
            	<a class="nav_btn normDecorA" href="{% url 'xadmin:index' %}">管理后台</a>
            	<a class="nav_btn normDecorA" href="{% url 'xadmin:logout' %}">退出登录</a>
            {% else %}
	            <a class="nav_btn normDecorA" href="{% url 'xadmin:login' %}">管理登录</a>
            {% endif %}
            {% if is_mobile %}
            	<a class="nav_btn normDecorA" href="?change_view_mode=mobile">切换手机版</a>
            {% endif %}

[07/Jun/2017 17:10:35] "GET /xadmin/login/ HTTP/1.1" 200 13557
[07/Jun/2017 17:10:35] "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
[07/Jun/2017 17:10:35] "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
[07/Jun/2017 17:10:35] "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
[07/Jun/2017 17:10:35] "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
[07/Jun/2017 17:10:35] "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
[07/Jun/2017 17:10:35] "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
[07/Jun/2017 17:10:35] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 20298
[07/Jun/2017 17:10:36] "GET /xadmin/jsi18n/ HTTP/1.1" 200 3378
[Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[07/Jun/2017 17:11:32] "GET /xadmin/ HTTP/1.1" 200 27050
Traceback (most recent call last):
  File "C:\Python27\lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "C:\Python27\lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "C:\Python27\lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "C:\Python27\lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "C:\Python27\lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "C:\Python27\lib\socket.py", line 328, in write
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
[07/Jun/2017 17:11:32] "GET /xadmin/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\site-packages\django-1.9.2-py2.7.egg\django\core\servers\basehttp.py", line 99, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
----------------------------------------
    self.wfile.close()
Exception happened during processing of request from ('127.0.0.1', 54434)
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
----------------------------------------
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by wgbbiao** [comment]
我遇到的大部是数据库连接的问题．

**Comment by toop** [comment]
(index):33 GET https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700 net::ERR_CONNECTION_TIMED_OUT
