### ISSUE TITLE
TypeError at /xadmin/users/userprofile/1/update/ render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by ShayChris** [sshwsfc/xadmin#426]
Request Method:	GET
Request URL:	http://127.0.0.1:8000/xadmin/users/userprofile/1/update/
Django Version:	1.11.4
Exception Type:	TypeError
Exception Value:	
render() got an unexpected keyword argument 'renderer'
Exception Location:	/Users/ShayChris/git/kmooc/extern_apps/xadmin/plugins/quickform.py in render, line 82
Python Executable:	/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Python Version:	3.6.1
Python Path:	
['/Users/ShayChris/git/kmooc/extern_apps',
 '/Users/ShayChris/git/kmooc/apps',
 '/Users/ShayChris/git/kmooc',
 '/Applications/PyCharm.app/Contents/helpers/pycharm',
 '/Users/ShayChris/git/kmooc',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Scrapy-1.4.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/service_identity-17.0.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyDispatcher-2.0.5-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/parsel-1.2.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six-1.10.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cssselect-1.0.1-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyOpenSSL-17.1.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/queuelib-1.4.2-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/w3lib-1.17.0-py3.6.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Twisted-17.5.0-py3.6-macosx-10.6-intel.egg',
 '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyasn1_modules-0.0.9-py3.6.egg']
Server time:	星期一, 7 八月 2017 14:26:56 +0800
Internal Server Error: /xadmin/users/userprofile/1/update/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 215, in render
    c = self.get_render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 134, in get_render
    actual_form.form_html = helper.render_layout(actual_form, node_context, template_pack=self.template_pack)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/helper.py", line 297, in render_layout
    template_pack=template_pack
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 138, in render
    return self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 358, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 358, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/utils.py", line 73, in render_field
    form, form_style, context, template_pack=template_pack,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 285, in render
    fields = self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crispy_forms/utils.py", line 162, in render_field
    html = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/template/base.py", line 993, in render
    bits.append(force_text(bit))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/html.py", line 385, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/forms/boundfield.py", line 127, in as_widget
    **kwargs
  File "/Users/ShayChris/git/kmooc/extern_apps/xadmin/plugins/quickform.py", line 82, in render
    self.widget.render(name, value, *args, **kwargs), '</div>'])
TypeError: render() got an unexpected keyword argument 'renderer'
我是在python3.6，django1.11.4下出现这个问题，找了很久都没找到解决办法，求指教

**Comment by wgbbiao** [comment]
升级到最新的xadmin试试。

**Comment by ShayChris** [comment]
最新的xadmin好像不支持django1.11，我这个是支持django1.11版本的分支

**Comment by wgbbiao** [comment]
主线支持1.11的．

**Comment by xulong3370** [comment]
![image](https://user-images.githubusercontent.com/19995841/43015995-e3bcc680-8c83-11e8-9e27-a863c65d6009.png)
![image](https://user-images.githubusercontent.com/19995841/43016012-f5fa26da-8c83-11e8-9d43-cd2e4d53094d.png)
我这么改就没报错了
