### ISSUE TITLE
引入xadmin错误

### ISSUE THREAD

**Issue by XdpAreKid** [sshwsfc/xadmin#448]
In settings.py
![ng gb l63 e02ldh117 _u](https://user-images.githubusercontent.com/22389436/30860360-732bf428-a2f9-11e7-9dd7-b78540f1e152.png)

In urls.py
![tim 20170926203008](https://user-images.githubusercontent.com/22389436/30860390-8a59097e-a2f9-11e7-8fb4-077b67e8cc41.png)

运行python manage.py runserver
报的错误为：
`Traceback (most recent call last):
  File "D:\pyenv\mxonline\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\pyenv\mxonline\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "D:\pyenv\mxonline\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "D:\pyenv\mxonline\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\pyenv\mxonline\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\pyenv\mxonline\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\pyenv\mxonline\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "D:\pyenv\mxonline\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "D:\pyenv\mxonline\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\pyenv\mxonline\lib\site-packages\xadmin-0.6.1-py3.6.egg\xadmin\__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "D:\pyenv\mxonline\lib\site-packages\xadmin-0.6.1-py3.6.egg\xadmin\sites.py", line 9, in <module>
    reload(sys)
NameError: name 'reload' is not defined`
![e_g 5l ul_x b7_4m6 bgtd](https://user-images.githubusercontent.com/22389436/30860420-a32e0a8a-a2f9-11e7-89bc-fb98a00a430f.png)

django==1.9.4,xadmin==0.6.1
运行环境是python3

**Comment by Chunmi-Tommy3886** [comment]
为什么关闭？我也碰到了。
