### ISSUE TITLE
在python3.6中，pip install xadmin 失败

### ISSUE THREAD

**Issue by lisi2016** [sshwsfc/xadmin#465]
Collecting xadmin
  Using cached xadmin-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Tang\AppData\Local\Temp\pip-build-byzus_ll\xadmin\setup.py", line 11, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 3444: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Tang\AppData\Local\Temp\pip-build-byzus_ll\xadmin\

不知道怎么回事。怎么才能解决了？

**Comment by wgbbiao** [comment]
pip install git+git://github.com/sshwsfc/xadmin.git
