### ISSUE TITLE
django 1.11.7 cannot import name 'lazy_property'

### ISSUE THREAD

**Issue by JohnChan0047** [sshwsfc/xadmin#468]
Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "E:\pylenv\cms\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\pylenv\cms\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.ready()
  File "E:\PycharmProjects\django_cms\extra_apps\xadmin\apps.py", line 14, in ready
    self.module.autodiscover()
  File "E:\PycharmProjects\django_cms\extra_apps\xadmin\__init__.py", line 49, in autodiscover
    register_builtin_plugins(site)
  File "E:\PycharmProjects\django_cms\extra_apps\xadmin\plugins\__init__.py", line 41, in register_builtin_plugins
    [import_module('xadmin.plugins.%s' % plugin) for plugin in PLUGINS if plugin not in exclude_plugins]
  File "E:\PycharmProjects\django_cms\extra_apps\xadmin\plugins\__init__.py", line 41, in <listcomp>
    [import_module('xadmin.plugins.%s' % plugin) for plugin in PLUGINS if plugin not in exclude_plugins]
  File "E:\pylenv\cms\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "E:\PycharmProjects\django_cms\extra_apps\xadmin\plugins\wizard.py", line 7, in <module>
    from formtools.wizard.storage import get_storage
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\pylenv\cms\lib\site-packages\formtools\wizard\storage\__init__.py", line 3, in <module>
    from .base import BaseStorage
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "E:\pylenv\cms\lib\site-packages\formtools\wizard\storage\base.py", line 3, in <module>
    from django.utils.functional import lazy_property
ImportError: cannot import name 'lazy_property'

**Comment by banjin** [comment]
you should updrade django-formtools
