### ISSUE TITLE
django2.0版本支持inline参数有问题

### ISSUE THREAD

**Issue by ferrisz** [sshwsfc/xadmin#491]

**Comment by wgbbiao** [comment]
截个图，发点代码．．

**Comment by hyzx86** [comment]
按照教程 直接运行报错

`PS D:\360安全浏览器下载\xadmin-master\demo_app> python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001D114703268>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\core\management\commands\runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\360安全浏览器下载\xadmin-master\demo_app\..\xadmin\models.py", line 8, in <module>
    from django.core.urlresolvers import NoReverseMatch, reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'`

**Comment by hyzx86** [comment]
这个是 linux 

`~/Desktop/xadmin-master/demo_app$ python3.5 manage.py  runserver 0.0.0.0:8008
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f09dfcea0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.5/dist-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/android/Desktop/xadmin-master/demo_app/../xadmin/models.py", line 8, in <module>
    from django.core.urlresolvers import NoReverseMatch, reverse
ImportError: No module named 'django.core.urlresolvers'
`

**Comment by Actmerce** [comment]
!['应该是这个问题'](https://actmerce.github.io/images/WechatIMG6.jpeg)

我也遇到类似的问题！

**Comment by zanderzhg** [comment]
@Actmerce 我一样,用的是官方demo也一样.

**Comment by Actmerce** [comment]
@zanderzhg 我翻了好久源码都没摸索到解决方法。感觉是样式加载出了问题。

**Comment by MyLong** [comment]
我将 xadmin.plugin.formset.js中75-76行修改成
           template = el.html(template); // decoded
            template = $($.parseHTML(template.html()));
OK了。
不过这个修复应该不是最好的，而且可能会有安全问题。不过能用了

**Comment by MyLong** [comment]
原因应该是原来的text函数仅仅会返回文本内容，会删除HTML标记。

**Comment by zanderzhg** [comment]
@MyLong 谢谢.

**Comment by Actmerce** [comment]
@MyLong 十分感谢！

**Comment by Actmerce** [comment]
@MyLong 我测试了一下，Inline 的 `style` 为默认值的时候功能基本正常了，其他`style`都有问题。估计还是得等修复了，先用默认样式顶一下。

**Comment by pingszi** [comment]
Inline 的 style 修改为默认值？是这样吗？
![image](https://user-images.githubusercontent.com/18133814/38864556-ad533454-426d-11e8-956e-e9ff5739b5a0.png)
