### ISSUE TITLE
ModuleNotFoundError: No module named 'future'

### ISSUE THREAD

**Issue by uptoheart** [sshwsfc/xadmin#539]
C:\Users\Doyle\PycharmProjects\DjangoTest>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Doyle\venv\DjangoTest\lib\site-packages\django\core\management\__init__.py", line 371,
in execute_from_command_line
    utility.execute()
  File "C:\Users\Doyle\venv\DjangoTest\lib\site-packages\django\core\management\__init__.py", line 347,
in execute
    django.setup()
  File "C:\Users\Doyle\venv\DjangoTest\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Doyle\venv\DjangoTest\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Doyle\venv\DjangoTest\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Doyle\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in i
mport_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Doyle\PycharmProjects\DjangoTest\xadmin\__init__.py", line 4, in <module>
    from xadmin.sites import AdminSite, site
  File "C:\Users\Doyle\PycharmProjects\DjangoTest\xadmin\sites.py", line 3, in <module>
    from future.utils import iteritems
ModuleNotFoundError: No module named 'future'

**Comment by uptoheart** [comment]
it'ok.you can slove it :  pip install --upgrade future
others: you should pip others framework. ex. six,django-import-export,django-reversion,
django-formtools,future,httplib2,six
