### ISSUE TITLE
django2.0下修改左侧菜单顺序报错

### ISSUE THREAD

**Issue by siskinc** [sshwsfc/xadmin#565]
```python
# 全局配置修改
class GlobalSetting(object):
    # 设置base_site.html的Title
    site_title = '四川志愿填报 管理平台'
    # 设置base_site.html的Footer
    site_footer = '四川志愿填报'
    menu_style = "accordion"

    def get_site_menu(self):
        return (
            {
                'title': '用户管理', 'menus': (
                {'title': '单用户管理', 'url': self.get_model_url(User, 'changelist')},
                {'title': '经销商管理', 'url': self.get_model_url(Agency, 'changelist')}
            )
            },
            {
                'title': '高校信息管理', 'menus': ({'url': self.get_model_url(UniversityInfo, 'changelist')})
            },
            {
                'title': '专业管理', 'menus': ({'url': self.get_model_url(Major, 'changelist')})
            },
            {
                'title': '省控线批次数据管理',
                'menus': ({'title': '普通类分年份分批次省控线', 'url': self.get_model_url(OrdinaryEachMinScore, 'changelist')},
                          {'title': '普通类分年份批线差', 'url': self.get_model_url(OrdinaryBatchScoreDistance, 'changelist')}),
            })
xadmin.site.register(views.CommAdminView, GlobalSetting)
```

``` error
Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/dashboard.py", line 593, in get
    return self.template_response('xadmin/views/dashboard.html', self.get_context())
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 49, in filter_chain
    return func()
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/dashboard.py", line 586, in get_context
    context = super(Dashboard, self).get_context()
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 49, in filter_chain
    return func()
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 410, in get_context
    menus = copy.copy(self.get_nav_menu())
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 49, in filter_chain
    return func()
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 345, in get_nav_menu
    get_url({'menus': site_menu}, had_urls)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 344, in get_url
    get_url(m, had_urls)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 344, in get_url
    get_url(m, had_urls)
  File "/home/siskinc/py/sczytb/venv/lib/python3.5/site-packages/xadmin/views/base.py", line 341, in get_url
    had_urls.append(menu['url'])
TypeError: string indices must be integers
[17/Apr/2018 21:35:41] "GET /xadmin/ HTTP/1.1" 500 222918
```

是我操作不对吗，但是我觉得自己应该是写正确了的

**Comment by siskinc** [comment]
自问自答吧，django2中不能类似于django1.11这样写menus，应该把menus改为menu就可以了

**Comment by siskinc** [comment]
视乎还是不行

**Comment by siskinc** [comment]
视乎还是不行

**Comment by siskinc** [comment]
```
    def get_site_menu(self):
        return (
            {
                'title': '用户管理', 'menus': (
                {'title': '单用户管理', 'url': self.get_model_url(User, 'changelist')},
                {'title': '经销商管理', 'url': self.get_model_url(Agency, 'changelist')}
            )},
            {
                'title': '高校信息管理', 'menus': ({'title': '高校信息', 'url': self.get_model_url(UniversityInfo, 'changelist')},{})
            },
            {
                'title': '专业管理', 'menus': ({'title': '专业信息', 'url': self.get_model_url(Major, 'changelist')},{})
            },
            {
                'title': '省控线批次数据管理',
                'menus': ({'title': '普通类分年份分批次省控线', 'url': self.get_model_url(OrdinaryEachMinScore, 'changelist')},
                         {'title': '普通类分年份批线差', 'url': self.get_model_url(OrdinaryBatchScoreDistance, 'changelist')}),
            })
```
我修改成这样，就不会报错了，我试了一下，在第二个和第三个，不加空的字典会报错，也就是如果menus只有一个就会报错

**Comment by siskinc** [comment]
好吧，视乎是把{}删除也可以，需要留逗号，Python的命名真是爽到爆啊
