### ISSUE TITLE
pip install 报编码错误，有个文件是不是编码有问题呢

### ISSUE THREAD

**Issue by r1912697476** [sshwsfc/xadmin#569]
pip install xadmin
Collecting xadmin
  Using cached https://files.pythonhosted.org/packages/1d/e9/2ac160c532d0d462142fa90aa86a0e317295e8d86fa4caf84d04f6e24c49/xadmin-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-9de1eiks\xadmin\setup.py", line 11, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 3444: illegal multibyte sequence

**Comment by CHANGSHAQI** [comment]
换djaogo2.0的安装方法
