### ISSUE TITLE
KeyError: 'LANGUAGE_CODE'

### ISSUE THREAD

**Issue by CUCmehp** [sshwsfc/xadmin#575]
when using xadmin django2.0, got following exception:

2018-05-09 07:52:53,289 DEBUG    Exception while resolving variable 'LANGUAGE_CODE' in template 'xadmin/views/model_form.html'.
Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'LANGUAGE_CODE'

**Comment by CUCmehp** [comment]
2018-05-09 07:52:53,289 DEBUG    Exception while resolving variable 'LANGUAGE_CODE' in template 'xadmin/views/model_form.html'.
Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'LANGUAGE_CODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'LANGUAGE_CODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'LANGUAGE_CODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [LANGUAGE_CODE] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000212E5C70488>>, 'request': <WSGIRequest: GET '/xadmin/courses/course/1/update/'>, 'user': <SimpleLazyObject: <UserProfile: CUCmehp>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000212E5CF15C0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000212E6D306D8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'admin_view': <xadmin.sites.coursescourseAdminUpdateAdminViewModelFormAdminViewModelAdminViewCommAdminViewBaseAdminViewBaseAdminObjectViewobject object at 0x00000212E6D307F0>, 'media': Media(css={'screen': ['/static/xadmin/vendor/bootstrap-image-gallery/css/bootstrap-image-gallery.css', '/static/xadmin/vendor/select2/select2.css', '/static/xadmin/vendor/selectize/selectize.css', '/static/xadmin/vendor/selectize/selectize.bootstrap3.css', '/static/xadmin/vendor/bootstrap-datepicker/css/datepicker.css', '/static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.css', '/static/xadmin/css/xadmin.form.css']}, js=['/static/xadmin/vendor/load-image/load-image.js', '/static/xadmin/vendor/bootstrap-image-gallery/js/bootstrap-image-gallery.js', '/static/xadmin/js/xadmin.plugin.portal.js', '/static/xadmin/vendor/selectize/selectize.js', '/static/xadmin/vendor/select2/select2.js', '/static/xadmin/vendor/select2/select2_locale_zh-hans.js', '/static/xadmin/js/xadmin.widget.select.js', '/static/xadmin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js', '/static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.js', '/static/xadmin/js/xadmin.widget.datetime.js', '/static/xadmin/js/xadmin.page.form.js']), 'base_template': 'xadmin/base_site.html', 'inline_formsets': [], 'menu_template': 'xadmin/includes/sitemenu_default.html', 'nav_menu': [{'title': 'Courses', 'menus': [{'title': '课程', 'url': '/xadmin/courses/course/', 'icon': None, 'order': 7, 'selected': True}], 'first_url': '/xadmin/courses/course/', 'selected': True}, {'title': 'Users', 'menus': [{'title': '用户信息', 'url': '/xadmin/users/userprofile/', 'icon': 'fa fa-user', 'order': 3}, {'title': '邮箱验证码', 'url': '/xadmin/users/emailverifyrecord/', 'icon': None, 'order': 5}, {'title': '轮播图', 'url': '/xadmin/users/banner/', 'icon': None, 'order': 6}], 'first_icon': 'fa fa-user', 'first_url': '/xadmin/users/userprofile/'}, {'title': '管理', 'menus': [{'title': '日志记录', 'url': '/xadmin/xadmin/log/', 'icon': 'fa fa-cog', 'order': 9}], 'first_icon': 'fa fa-cog', 'first_url': '/xadmin/xadmin/log/'}, {'title': '认证和授权', 'menus': [{'title': '组', 'url': '/xadmin/auth/group/', 'icon': 'fa fa-group', 'order': 2}, {'title': '权限', 'url': '/xadmin/auth/permission/', 'icon': 'fa fa-lock', 'order': 4}], 'first_icon': 'fa fa-group', 'first_url': '/xadmin/auth/group/'}], 'site_title': 'Django Xadmin', 'site_footer': '我的公司', 'breadcrumbs': [{'url': '/xadmin/', 'title': '首页'}, {'title': '课程', 'url': '/xadmin/courses/course/'}, {'title': 'Course object (1)', 'url': '/xadmin/courses/course/1/update/'}], 'opts': <Options for Course>, 'app_label': 'courses', 'model_name': 'course', 'verbose_name': '课程', 'model_icon': None, 'form': <CourseForm bound=False, valid=Unknown, fields=(name;desc;detail;degree;learn_times;students;fav_nums;image;click_nums;add_time)>, 'original': <Course: Course object (1)>, 'show_delete': True, 'add': False, 'change': True, 'errors': [], 'has_add_permission': True, 'has_view_permission': True, 'has_change_permission': True, 'has_delete_permission': True, 'has_file_field': True, 'has_absolute_url': False, 'form_url': '', 'content_type_id': 11, 'save_as': False, 'save_on_top': False, 'onclick_attrib': '', 'show_delete_link': True, 'show_save_as_new': False, 'show_save_and_add_another': True, 'show_save_and_continue': True, 'show_save': True, 'delete_url': '/xadmin/courses/course/1/delete/', 'title': '修改 Course object (1)', 'object_id': '1'}]
2018-05-09 07:52:53,291 DEBUG    Exception while resolving variable 'LANGUAGE_BIDI' in template 'xadmin/views/model_form.html'.
Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'LANGUAGE_BIDI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'LANGUAGE_BIDI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'LANGUAGE_BIDI'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [LANGUAGE_BIDI] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00000212E5C70488>>, 'request': <WSGIRequest: GET '/xadmin/courses/course/1/update/'>, 'user': <SimpleLazyObject: <UserProfile: CUCmehp>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000212E5CF15C0>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000212E6D306D8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'admin_view': <xadmin.sites.coursescourseAdminUpdateAdminViewModelFormAdminViewModelAdminViewCommAdminViewBaseAdminViewBaseAdminObjectViewobject object at 0x00000212E6D307F0>, 'media': Media(css={'screen': ['/static/xadmin/vendor/bootstrap-image-gallery/css/bootstrap-image-gallery.css', '/static/xadmin/vendor/select2/select2.css', '/static/xadmin/vendor/selectize/selectize.css', '/static/xadmin/vendor/selectize/selectize.bootstrap3.css', '/static/xadmin/vendor/bootstrap-datepicker/css/datepicker.css', '/static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.css', '/static/xadmin/css/xadmin.form.css']}, js=['/static/xadmin/vendor/load-image/load-image.js', '/static/xadmin/vendor/bootstrap-image-gallery/js/bootstrap-image-gallery.js', '/static/xadmin/js/xadmin.plugin.portal.js', '/static/xadmin/vendor/selectize/selectize.js', '/static/xadmin/vendor/select2/select2.js', '/static/xadmin/vendor/select2/select2_locale_zh-hans.js', '/static/xadmin/js/xadmin.widget.select.js', '/static/xadmin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js', '/static/xadmin/vendor/bootstrap-clockpicker/bootstrap-clockpicker.js', '/static/xadmin/js/xadmin.widget.datetime.js', '/static/xadmin/js/xadmin.page.form.js']), 'base_template': 'xadmin/base_site.html', 'inline_formsets': [], 'menu_template': 'xadmin/includes/sitemenu_default.html', 'nav_menu': [{'title': 'Courses', 'menus': [{'title': '课程', 'url': '/xadmin/courses/course/', 'icon': None, 'order': 7, 'selected': True}], 'first_url': '/xadmin/courses/course/', 'selected': True}, {'title': 'Users', 'menus': [{'title': '用户信息', 'url': '/xadmin/users/userprofile/', 'icon': 'fa fa-user', 'order': 3}, {'title': '邮箱验证码', 'url': '/xadmin/users/emailverifyrecord/', 'icon': None, 'order': 5}, {'title': '轮播图', 'url': '/xadmin/users/banner/', 'icon': None, 'order': 6}], 'first_icon': 'fa fa-user', 'first_url': '/xadmin/users/userprofile/'}, {'title': '管理', 'menus': [{'title': '日志记录', 'url': '/xadmin/xadmin/log/', 'icon': 'fa fa-cog', 'order': 9}], 'first_icon': 'fa fa-cog', 'first_url': '/xadmin/xadmin/log/'}, {'title': '认证和授权', 'menus': [{'title': '组', 'url': '/xadmin/auth/group/', 'icon': 'fa fa-group', 'order': 2}, {'title': '权限', 'url': '/xadmin/auth/permission/', 'icon': 'fa fa-lock', 'order': 4}], 'first_icon': 'fa fa-group', 'first_url': '/xadmin/auth/group/'}], 'site_title': 'Django Xadmin', 'site_footer': '我的公司', 'breadcrumbs': [{'url': '/xadmin/', 'title': '首页'}, {'title': '课程', 'url': '/xadmin/courses/course/'}, {'title': 'Course object (1)', 'url': '/xadmin/courses/course/1/update/'}], 'opts': <Options for Course>, 'app_label': 'courses', 'model_name': 'course', 'verbose_name': '课程', 'model_icon': None, 'form': <CourseForm bound=False, valid=Unknown, fields=(name;desc;detail;degree;learn_times;students;fav_nums;image;click_nums;add_time)>, 'original': <Course: Course object (1)>, 'show_delete': True, 'add': False, 'change': True, 'errors': [], 'has_add_permission': True, 'has_view_permission': True, 'has_change_permission': True, 'has_delete_permission': True, 'has_file_field': True, 'has_absolute_url': False, 'form_url': '', 'content_type_id': 11, 'save_as': False, 'save_on_top': False, 'onclick_attrib': '', 'show_delete_link': True, 'show_save_as_new': False, 'show_save_and_add_another': True, 'show_save_and_continue': True, 'show_save': True, 'delete_url': '/xadmin/courses/course/1/delete/', 'title': '修改 Course object (1)', 'object_id': '1'}]
2018-05-09 07:52:53,292 DEBUG    Exception while resolving variable 'LANGUAGE_BIDI' in template 'xadmin/views/model_form.html'.
Traceback (most recent call last):
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "D:\hup\workspace\python_work\envs\env-edu\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'LANGUAGE_BIDI'

**Comment by sjtechyh** [comment]
同样的问题。。。xadmin的bug实在太多了。。。从安装到配置几乎没有哪个环节是顺利的。。。希望早日解决

**Comment by supersheng** [comment]
有结果吗？
