### ISSUE TITLE
Django2分支+python3.6+gunicorn 导出表格存在中文会报错

### ISSUE THREAD

**Issue by Flamingo-Chen** [sshwsfc/xadmin#634]
Error handling request /admin/app/user/?_do_=export&export_type=xml&export_xml_format=on&all=on
Traceback (most recent call last):
  File "/home/ever/.virtualenvs/ever/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ever/.virtualenvs/ever/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/home/ever/.virtualenvs/ever/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 333, in write
    self.send_headers()
  File "/home/ever/.virtualenvs/ever/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 329, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "ascii"))
  File "/home/ever/.virtualenvs/ever/lib/python3.6/site-packages/gunicorn/util.py", line 507, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 192-197: ordinal not in range(128)

**Comment by alexsilva** [comment]
Related: https://github.com/benoitc/gunicorn/issues/1214
