### ISSUE TITLE
importexport不能使用列名为verbose_name的excel

### ISSUE THREAD

**Issue by chesterlyd** [sshwsfc/xadmin#641]
屏幕截图
------
![image](https://user-images.githubusercontent.com/10460338/48955107-4b6f2a00-ef87-11e8-96c5-c8d8f0b39ad1.png)
------
导入时字段名不能显示verbose_name的名字，并且excel的列名不能使用verbose_name的名称

| 软件包 | 版本号 |
| ------ | ------|
| python | 3.6 |
| django | 2.1 |
| import_port | 最新 |
| xadmin | 2.0.1 |

**Comment by bigwboy** [comment]
同上

**Comment by bigwboy** [comment]
解决了 告知一下，顺便问下 如果导入的表中数据关联其他表，一直报错：行号: 1 - NOT NULL constraint failed: test1_tes2.XXX_id
1.0,xxx, WWW
Traceback (most recent call last):
File "C:\Users\watone-test\venv\untitled10\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
return self.cursor.execute(sql, params)
File "C:\Users\watone-test\venv\untitled10\lib\site-packages\django\db\backends\sqlite3\base.py", line 296, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: test1_tes2.XXX_id
