### ISSUE TITLE
xadmin适配Django2.2以上吗？

### ISSUE THREAD

**Issue by yanlianhanlin** [sshwsfc/xadmin#672]
xadmin适配Django2.2以上吗？

**Comment by PengLicn** [comment]
这个没试过，我刚开始学，用Django2.1.7搭建了个小系统，不好意思不能帮到你！


------------------ 原始邮件 ------------------
发件人: "yanlianhanlin"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 上午8:31
收件人: "sshwsfc/xadmin"<xadmin@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [sshwsfc/xadmin] xadmin适配Django2.2以上吗？ (#672)




xadmin适配Django2.2以上吗？

**Comment by MistBirds** [comment]
django2.2我尝试了半天时间，还是失败了，问题解决了一个又出现另一个，django2.1.x没尝试过

**Comment by 51sbd** [comment]
ImportError: No module named urls.base

**Comment by Har-zheng** [comment]
我也是使用最新的django2.2配合xadmin使用 很长时间没法适配  把django回退2.1才适配了  期待大神能够解决.

**Comment by wgbbiao** [comment]
pip3 install xadmin2 应该 可以使用。

**Comment by xx-zhang** [comment]
django>2.0 and django<=2.0.12

**Comment by xx-zhang** [comment]
> django>2.0 and django<=2.0.12

主要是 weight 会出现问题

**Comment by oliverstian** [comment]
可以用啊，你得按pip install git+git://github.com/sshwsfc/xadmin.git@django2下载，我的django2.2，用得没毛病

**Comment by AeroYoung** [comment]
各种各样的bug一大堆

**Comment by shenmadouyaowen** [comment]
无法用,上来就这个错了
`E:\python\blog>python manage.py runserver
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\xadmin\models.py", line 8, in <module>
    from django.core.urlresolvers import NoReverseMatch, reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'`

**Comment by ctenix** [comment]
目前用的dj2.2+xadmin,有一些错误需要修正，修复就可以用了

**Comment by xifarm** [comment]
新学习django 3.0.4， xadmin尝试了2次，各自坑，项目run不起来。

放弃xadmin。

**Comment by L1uNan** [comment]
> 新学习django 3.0.4， xadmin尝试了2次，各自坑，项目run不起来。
> 
> 放弃xadmin。

目测xadmin不支持django>2.1  会报错  需要手动改它的源码
