### ISSUE TITLE
LookupError: No installed app with label 'reversion'.

### ISSUE THREAD

**Issue by haiya512** [sshwsfc/xadmin#731]
Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\apps\registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'reversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\dashboard.py", line 593, in get
    return self.template_response('xadmin/views/dashboard.html', self.get_context())
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\dashboard.py", line 586, in get_context
    context = super(Dashboard, self).get_context()
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 63, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 62, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 410, in get_context
    menus = copy.copy(self.get_nav_menu())
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\xadmin\views\base.py", line 373, in get_nav_menu
    app_title = smart_text(apps.get_app_config(app_label).verbose_name)
  File "C:\Users\Lenovo\code\ft\venv\lib\site-packages\django\apps\registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'reversion'.
[24/Aug/2021 15:59:27] "GET /xadmin/ HTTP/1.1" 500 183939

**Comment by alexsilva** [comment]
Install [requirements ](https://github.com/sshwsfc/xadmin/blob/master/requirements.txt)
